name: CloudFront

on: 
  push:
    branches: [master]
  schedule:
    # 时间是按 UTC 设置
    - cron: 0 12 * * *
jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install zmap 
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Scan
      run: |
        sudo python scan-cloudfront.py iplist.txt 200

    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: cloudfront-cn-ips.txt
        path: result.txt
